base/urls.py
from django.urls import path

from . import views

app_name = "base"

urlpatterns = [
    path("", views.index, name="index"),
]

user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
]

xyz/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("accounts/", include("user.urls")),
    # path("facebook", include("social_django.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/models.py
"""model layer of the user application"""
from django.db import models

# Create your models here.

user/forms.py
"""form layer of the user application"""
from django import forms
from django.contrib.auth.models import User


# Create your forms here

base/views.py
"""base application view layer"""
from django.shortcuts import render

# Create your views here.
def index(request):
    """displays the landing page of the base app"""
    context = {}
    return render(request, "base/index.html", context)

user/views.py
"""user controller"""
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages


# Create your views here.
def logout_user(request):
    """destroy session for requested request"""
    logout(request)
    return HttpResponseRedirect(reverse("base:index"))


def login_user(request):
    """logs a user in into the session"""

    # when method is post
    if request.method == "POST":

        # get username and password
        username = request.POST.get("username").lower()
        password = request.POST.get("password")
        remember_me = request.POST.get("remember_me")
        # check for username and password
        if not username:
            messages.error(request, "Please provide your username.")
        elif not password:
            messages.error(request, "Please provide your password.")
        else:
            # try to authenticate user
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                if not remember_me:
                    request.session.set_expiry(0)
                return HttpResponseRedirect(reverse("base:index"))
            messages.error(request, "Invalid username and/or password.")
    # when method is not post
    context = {"title": "login"}
    return render(request, "user/login.html", context)


def register_user(request):
    """register and login a new user"""
    # when method is post
    if request.method == "POST":
        username = request.POST.get("username").lower()
        password = request.POST.get("password")
        confirmation = request.POST.get("confirmation")
        if not username:
            messages.error(request, "Please provide your username.")
        elif not password:
            messages.error(request, "Please provide your password.")
        elif not confirmation or confirmation != password:
            messages.error(request, "Please confirm your passowrd.")
        elif User.objects.filter(username=username).exists():
            messages.error(request, "Username already taken")
        else:
            user = User.objects.create(
                username=username, email=username, password=password
            )
            login(request, user)
            messages.success(request, "Registered and logged in successfully.")
            return HttpResponseRedirect(reverse("base:index"))
    context = {"title": "register"}
    return render(request, "user/register.html", context)


class Password:
    """Password object which has several validation methods"""

    def __init__(self, arg):
        self.arg = arg

    def __str__(self):
        """returns the string representation of the password"""
        return f"{self.arg}"

    def is_numeric(self):
        """returns true if password is entirely numeric\notherwise false"""
        return self.arg.isdigit()

    def is_strong(self):
        """return true if password has any of !@#$%^&*, otherwise false"""
        return any(char in "!@#$%^&*" for char in self.arg)

    def has_valid_length(self):
        """returns true if length is greater than or equal to 8, otherwise false"""
        return len(self.arg) > 7

templates/base/index.html
{% extends "layout.html" %}
{% block main %}
<div class="container py-5">
    <div class="row">
        <div class="text-center">{% now "M d g:i A" %}</div>
        <div class="col-8 offset-2">
            {% if messages %}
            {% for message in messages %}
            <div role=alert class="alert alert-{{ message.tags }} alert-dismissible show fade">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss=alert aria-label=Close></button>
            </div>
            {% endfor %}
            {% endif %}
            <div class="card">
                <div class="card-header">
                    Welcome!
                </div>
                <div class="card-body">
                    <div class="card-text">Hello {{ request.user.get_username|default:"World" }}</div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
<footer class="container-fluid text-bg-primary py-3">
    <div class="row">
        <div class="col-12">
            <div class="text-center">
                copyright &copy; {% now "Y" %}
            </div>
        </div>
    </div>
</footer>

templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <title>{% block title %}{{ title|default:"home"|title }}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    {% block head %}{% endblock %}
</head>

<body class="bg-light border-start border-end border-primary border-5">
    {% include 'navbar.html' %}
    <main style="min-height:81.7vh;">
        {% block main %}{% endblock %}
    </main>
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand navbar-dark bg-primary sticky-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'base:index' %}">&lt;/&gt;</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link{% if not title %} active{% endif %}" aria-current="page" href="{% url 'base:index' %}">Home</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link{% if title == 'login' %} active{% endif %}" href="{% url 'user:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{% if title == 'register' %} active{% endif %}" href="{% url 'user:register' %}">Register</a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Settings
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="#">Dashboard</a></li>
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">cPanel</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item{% if title == 'logout' %} active{% endif %}" href="{% url 'user:logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/user/login.html
{% extends "layout.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'user/css/user.css' %}">
<style>
    .target { width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:10px 0 20px; } 
</style>
{% endblock %}
{% block main %}
<div class="container pt-5">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
            {% if messages %}
            {% for message in messages %}
            <div role=alert class="alert alert-{{ message.tags }} alert-dismissible show fade">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss=alert aria-label=Close></button>
            </div>
            {% endfor %}
            {% endif %}
            <form class="login" method="post">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-normal text-center">Login</h1>
                <div class="btn-group w-100">
                    <a href="#" class="btn btn-sm btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                        </svg>
                        Login with Facebook
                    </a>
                </div>
                <div class="my-3 text-center target"><span class="px-3 bg-light">or</span></div>
                <div class="form-floating">
                    <input type="email" class="form-control rounded-bottom-0" data-message="Please enter your email" id="email" placeholder="name@example.com" name="username">
                    <label for="email">Email address</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" name=password class="form-control rounded-top-0" data-message="Please type your password" id="password" placeholder="Password">
                    <label for="password">Password</label>
                </div>
                <div class="form-check form-switch mb-3">
                    <input class="form-check-input" type="checkbox" name="remember_me" role="switch" id="remember-me">
                    <label class="form-check-label" for="remember-me">Remember me</label>
                </div>
                <button class="btn w-100 btn-primary" type="submit" formaction="{% url 'user:login' %}">Login</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script src="{% static 'user/js/user.js' %}"></script>
{% endblock %}

templates/user/profile.html
{% extends "layout.html" %}
{% load static %}
{% block head %}
    <style>
        .profile {
            transition-duration: 500ms;
            transition-timing-function: ease-in;
        }
        .profile:hover {
            border-radius: 50% !important;
        }
    </style>
    {% endblock %}
{% block main %}
<div class="container py-5">
    <div class="row">
        <div class="col-12">
            <div class="rounded bg-white-50 shadow p-3">
                <div class="row g-2 align-items-center">
                    <div class="col-12 col-md-4 col-lg-2">
                        <div class="text-center">
                            <img src="{{ request.user.profile.get_profile_picture.url }}" class="rounded profile" width="100" height="100" alt="">
                            <form action="{% url 'user:profile' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="file" hidden name="profile_picture" id="profile_picture" onchange="showBtn('#submit');removeBtn('#profile_picture_btn');">
                                <label for="profile_picture" id="profile_picture_btn"  class="btn btn-sm btn-success mb-3">change</label>
                                <button id="submit" type="submit" class="btn btn-sm btn-primary d-none">Update</button>
                            </form>
                        </div>
                    </div>
                    <div class="col-12 col-md-8 col-lg-10">
                        <h3>{{ request.user.get_username|upper }}</h3>
                        <div class="list-group list-group-flush">
                            <div class="list-group-item"><span class="text-muted">First Name:</span> {{ request.user.first_name }}</div>
                            <div class="list-group-item"><span class="text-muted">Last Name:</span> {{ request.user.last_name }}</div>
                            <div class="list-group-item"><span class="text-muted">Email:</span> {{ request.user.email }}</div>
                            <div class="list-group-item"><span class="text-muted">Password:</span> ********</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}
{% block script %}
    <script>
        function showBtn(selector) {
            document.querySelector(selector).classList.remove('d-none');
        }
        function removeBtn(selector) {
            document.querySelector(selector).classList.add('d-none');
        }
    </script>
    {% endblock %}

templates/user/register.html
{% extends "layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'user/css/user.css' %}">
    {% endblock %}
{% block main %}
<div class="container pt-5">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
        {% if messages %}
            {% for message in messages %}
                <div role=alert class="alert alert-{{ message.tags }} alert-dismissible show fade">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss=alert aria-label=Close></button>
                </div>
            {% endfor %}
        {% endif %}
            <form method="post">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-normal text-center">Register</h1>
                <div class="form-floating">
                    <input type="email" class="form-control rounded-bottom-0" data-message="Please enter your email" id="email" placeholder="name@example.com" name="username">
                    <label for="email">Email address</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control rounded-top-0 rounded-bottom-0" id="password" name="password" placeholder="Password">
                    <label for="password">Password</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" class="form-control rounded-top-0" id="confrim_password" name="confirmation" placeholder="Confirm Password">
                    <label for="confrim_password">Confirm Password</label>
                </div>
                <div class="form-check form-switch mb-3">
                    <input class="form-check-input" type="checkbox" name="remember_me" role="switch" id="remember-me">
                    <label class="form-check-label" for="remember-me">Remember me</label>
                </div>
                <button class="btn w-100 btn-primary" type="submit" formaction="{% url 'user:register' %}">Register</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
    <script src="{% static 'user/js/user.js' %}"></script>
{% endblock %}